version: "2"

services:

  php:
    image: silintl/php7:7.4
    volumes:
      - ./:/data
    extra_hosts:
     - "trusted_host.org:10.0.1.1"
     - "untrusted_host.org:22.0.1.1"
    working_dir: /data
