services:
  php:
    image: silintl/php8:8.3
    platform: linux/amd64
    volumes:
      - ./:/data
    extra_hosts:
      - "trusted_host.org:10.0.1.1"
      - "untrusted_host.org:22.0.1.1"
    working_dir: /data
